import { Knex, QueryBuilder } from "knex";

type ComparisonOperator = '=' | '>' | '>=' | '<' | '<=' | '<>';
type QueryCallback = (builder: QueryBuilder) => void;

export interface OeremQuery<T> {
    select(...columnNames: any[]): OeremQuery<T>;
    select(subQueryBuilders: any[]): OeremQuery<T>;
    select(aliases: string | Record<string, string>): OeremQuery<T>;
    select(columnName: "*"): OeremQuery<T>;
    // select(columnNames: readonly ColNameUT[]): OeremQuery<T>;

    select(columnNames: any[]): OeremQuery<T>;
    distinct(columnName: "*"): OeremQuery<T>;
    // distinct(columnNames: readonly ColNameUT[]): OeremQuery<T>;

    distinct(columnNames: any[]): OeremQuery<T>;
    distinct(columnName: any): OeremQuery<T>;
    // distinctOn(columnNames: readonly ColNameUT[]): OeremQuery<T>;

    distinctOn(columnNames: readonly string[]): OeremQuery<T>;
    join(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // join(tableName: TTable, clause: any): OeremQuery<T>;
    join(tableName: QueryCallback, clause: any): OeremQuery<T>;
    join(tableName: QueryCallback, columns: any): OeremQuery<T>;
    join(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    join(tableName: string, column1: string, column2: string): OeremQuery<T>;
    // join(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    join(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    join(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // join(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    join(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    joinRaw(tableName: string, binding: any[]): OeremQuery<T>;
    innerJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // innerJoin(tableName: TTable, clause: any): OeremQuery<T>;
    innerJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    innerJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    innerJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // innerJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    innerJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    innerJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // innerJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    innerJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    leftJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // leftJoin(tableName: TTable, clause: any): OeremQuery<T>;
    leftJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    leftJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    leftJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // leftJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    leftJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    leftJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // leftJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    leftJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    leftOuterJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // leftOuterJoin(tableName: TTable, clause: any): OeremQuery<T>;
    leftOuterJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    leftOuterJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    leftOuterJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // leftOuterJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    leftOuterJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    leftOuterJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // leftOuterJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    leftOuterJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    rightJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // rightJoin(tableName: TTable, clause: any): OeremQuery<T>;
    rightJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    rightJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    rightJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // rightJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    rightJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    rightJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // rightJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    rightJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    rightOuterJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // rightOuterJoin(tableName: TTable, clause: any): OeremQuery<T>;
    rightOuterJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    rightOuterJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    rightOuterJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // rightOuterJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    rightOuterJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    rightOuterJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // rightOuterJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    rightOuterJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    outerJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // outerJoin(tableName: TTable, clause: any): OeremQuery<T>;
    outerJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    outerJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    outerJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // outerJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    outerJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    outerJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // outerJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    outerJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    fullOuterJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // fullOuterJoin(tableName: TTable, clause: any): OeremQuery<T>;
    fullOuterJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    fullOuterJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    fullOuterJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // fullOuterJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    fullOuterJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    fullOuterJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // fullOuterJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    fullOuterJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    crossJoin(raw: string | Knex.Raw<any>): OeremQuery<T>;
    // crossJoin(tableName: TTable, clause: any): OeremQuery<T>;
    crossJoin(tableName: QueryCallback, clause: any): OeremQuery<T>;
    crossJoin(tableName: QueryCallback, columns: any): OeremQuery<T>;
    crossJoin(tableName: QueryCallback, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // crossJoin(tableName: TTable2, column1: keyof T, column2: keyof T): OeremQuery<T>;
    crossJoin(tableName: QueryCallback, column1: string, column2: string): OeremQuery<T>;
    crossJoin(tableName: QueryCallback, column1: string, raw: string | Knex.Raw<any>): OeremQuery<T>;
    // crossJoin(tableName: TTable2, column1: keyof T, operator: string, column2: keyof T): OeremQuery<T>;
    crossJoin(tableName: QueryCallback, column1: string, operator: string, column2: string): OeremQuery<T>;
    jsonExtract(column: any, path: string, alias: string, singleValue: boolean): OeremQuery<T>;
    // jsonExtract(column: JsonExtraction[] | any[][], singleValue: boolean): OeremQuery<T>;
    where(raw: string | Knex.Raw<any>): OeremQuery<T>;
    where(callback: QueryCallback): OeremQuery<T>;
    where(object: any): OeremQuery<T>;
    where(columnName: keyof T, value: any): OeremQuery<T>;
    where(columnName: string, value: any): OeremQuery<T>;
    where(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    where(columnName: string, operator: string, value: any): OeremQuery<T>;
    where(left: any, operator: string, right: any): OeremQuery<T>;
    where(condition: boolean): OeremQuery<T>;
    where(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    where(columnName: keyof T): OeremQuery<T>;
    where(columnName: string): OeremQuery<T>;
    andWhere(raw: string | Knex.Raw<any>): OeremQuery<T>;
    andWhere(callback: QueryCallback): OeremQuery<T>;
    andWhere(object: any): OeremQuery<T>;
    andWhere(columnName: keyof T, value: any): OeremQuery<T>;
    andWhere(columnName: string, value: any): OeremQuery<T>;
    andWhere(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    andWhere(columnName: string, operator: string, value: any): OeremQuery<T>;
    andWhere(left: any, operator: string, right: any): OeremQuery<T>;
    andWhere(condition: boolean): OeremQuery<T>;
    andWhere(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    andWhere(columnName: keyof T): OeremQuery<T>;
    andWhere(columnName: string): OeremQuery<T>;
    orWhere(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orWhere(callback: QueryCallback): OeremQuery<T>;
    orWhere(object: any): OeremQuery<T>;
    orWhere(columnName: keyof T, value: any): OeremQuery<T>;
    orWhere(columnName: string, value: any): OeremQuery<T>;
    orWhere(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    orWhere(columnName: string, operator: string, value: any): OeremQuery<T>;
    orWhere(left: any, operator: string, right: any): OeremQuery<T>;
    orWhere(condition: boolean): OeremQuery<T>;
    orWhere(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orWhere(columnName: keyof T): OeremQuery<T>;
    orWhere(columnName: string): OeremQuery<T>;
    whereNot(raw: string | Knex.Raw<any>): OeremQuery<T>;
    whereNot(callback: QueryCallback): OeremQuery<T>;
    whereNot(object: any): OeremQuery<T>;
    whereNot(columnName: keyof T, value: any): OeremQuery<T>;
    whereNot(columnName: string, value: any): OeremQuery<T>;
    whereNot(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    whereNot(columnName: string, operator: string, value: any): OeremQuery<T>;
    whereNot(left: any, operator: string, right: any): OeremQuery<T>;
    whereNot(condition: boolean): OeremQuery<T>;
    whereNot(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    whereNot(columnName: keyof T): OeremQuery<T>;
    whereNot(columnName: string): OeremQuery<T>;
    andWhereNot(raw: string | Knex.Raw<any>): OeremQuery<T>;
    andWhereNot(callback: QueryCallback): OeremQuery<T>;
    andWhereNot(object: any): OeremQuery<T>;
    andWhereNot(columnName: keyof T, value: any): OeremQuery<T>;
    andWhereNot(columnName: string, value: any): OeremQuery<T>;
    andWhereNot(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    andWhereNot(columnName: string, operator: string, value: any): OeremQuery<T>;
    andWhereNot(left: any, operator: string, right: any): OeremQuery<T>;
    andWhereNot(condition: boolean): OeremQuery<T>;
    andWhereNot(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    andWhereNot(columnName: keyof T): OeremQuery<T>;
    andWhereNot(columnName: string): OeremQuery<T>;
    orWhereNot(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orWhereNot(callback: QueryCallback): OeremQuery<T>;
    orWhereNot(object: any): OeremQuery<T>;
    orWhereNot(columnName: keyof T, value: any): OeremQuery<T>;
    orWhereNot(columnName: string, value: any): OeremQuery<T>;
    orWhereNot(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    orWhereNot(columnName: string, operator: string, value: any): OeremQuery<T>;
    orWhereNot(left: any, operator: string, right: any): OeremQuery<T>;
    orWhereNot(condition: boolean): OeremQuery<T>;
    orWhereNot(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orWhereNot(columnName: keyof T): OeremQuery<T>;
    orWhereNot(columnName: string): OeremQuery<T>;
    whereRaw(condition: boolean): OeremQuery<T>;
    whereRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    whereRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orWhereRaw(condition: boolean): OeremQuery<T>;
    orWhereRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orWhereRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    andWhereRaw(condition: boolean): OeremQuery<T>;
    andWhereRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    andWhereRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    whereWrapped(callback: QueryCallback): OeremQuery<T>;
    havingWrapped(callback: QueryCallback): OeremQuery<T>;
    whereExists(callback: QueryCallback): OeremQuery<T>;
    whereExists(query: any): OeremQuery<T>;
    orWhereExists(callback: QueryCallback): OeremQuery<T>;
    orWhereExists(query: any): OeremQuery<T>;
    whereNotExists(callback: QueryCallback): OeremQuery<T>;
    whereNotExists(query: any): OeremQuery<T>;
    orWhereNotExists(callback: QueryCallback): OeremQuery<T>;
    orWhereNotExists(query: any): OeremQuery<T>;
    whereIn(columnName: keyof T, values: QueryCallback): OeremQuery<T>;
    whereIn(columnName: string, values: QueryCallback): OeremQuery<T>;
    whereIn(columnNames: keyof T, values: QueryCallback): OeremQuery<T>;
    whereIn(columnNames: readonly string[], values: QueryCallback): OeremQuery<T>;
    whereIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    whereIn(columnName: string, values: any[]): OeremQuery<T>;
    whereIn(columnNames: keyof T, values: keyof T): OeremQuery<T>;
    whereIn(columnNames: readonly string[], values: any): OeremQuery<T>;
    orWhereIn(columnName: keyof T, values: QueryCallback): OeremQuery<T>;
    orWhereIn(columnName: string, values: QueryCallback): OeremQuery<T>;
    orWhereIn(columnNames: keyof T, values: QueryCallback): OeremQuery<T>;
    orWhereIn(columnNames: readonly string[], values: QueryCallback): OeremQuery<T>;
    orWhereIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    orWhereIn(columnName: string, values: any[]): OeremQuery<T>;
    orWhereIn(columnNames: keyof T, values: keyof T): OeremQuery<T>;
    orWhereIn(columnNames: readonly string[], values: any): OeremQuery<T>;
    whereNotIn(columnName: keyof T, values: QueryCallback): OeremQuery<T>;
    whereNotIn(columnName: string, values: QueryCallback): OeremQuery<T>;
    whereNotIn(columnNames: keyof T, values: QueryCallback): OeremQuery<T>;
    whereNotIn(columnNames: readonly string[], values: QueryCallback): OeremQuery<T>;
    whereNotIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    whereNotIn(columnName: string, values: any[]): OeremQuery<T>;
    whereNotIn(columnNames: keyof T, values: keyof T): OeremQuery<T>;
    whereNotIn(columnNames: readonly string[], values: any): OeremQuery<T>;
    orWhereNotIn(columnName: keyof T, values: QueryCallback): OeremQuery<T>;
    orWhereNotIn(columnName: string, values: QueryCallback): OeremQuery<T>;
    orWhereNotIn(columnNames: keyof T, values: QueryCallback): OeremQuery<T>;
    orWhereNotIn(columnNames: readonly string[], values: QueryCallback): OeremQuery<T>;
    orWhereNotIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    orWhereNotIn(columnName: string, values: any[]): OeremQuery<T>;
    orWhereNotIn(columnNames: keyof T, values: keyof T): OeremQuery<T>;
    orWhereNotIn(columnNames: readonly string[], values: any): OeremQuery<T>;
    whereLike(raw: string | Knex.Raw<any>): OeremQuery<T>;
    whereLike(callback: QueryCallback): OeremQuery<T>;
    whereLike(object: any): OeremQuery<T>;
    whereLike(columnName: keyof T, value: any): OeremQuery<T>;
    whereLike(columnName: string, value: any): OeremQuery<T>;
    whereLike(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    whereLike(columnName: string, operator: string, value: any): OeremQuery<T>;
    whereLike(left: any, operator: string, right: any): OeremQuery<T>;
    whereLike(condition: boolean): OeremQuery<T>;
    whereLike(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    whereLike(columnName: keyof T): OeremQuery<T>;
    whereLike(columnName: string): OeremQuery<T>;
    andWhereLike(raw: string | Knex.Raw<any>): OeremQuery<T>;
    andWhereLike(callback: QueryCallback): OeremQuery<T>;
    andWhereLike(object: any): OeremQuery<T>;
    andWhereLike(columnName: keyof T, value: any): OeremQuery<T>;
    andWhereLike(columnName: string, value: any): OeremQuery<T>;
    andWhereLike(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    andWhereLike(columnName: string, operator: string, value: any): OeremQuery<T>;
    andWhereLike(left: any, operator: string, right: any): OeremQuery<T>;
    andWhereLike(condition: boolean): OeremQuery<T>;
    andWhereLike(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    andWhereLike(columnName: keyof T): OeremQuery<T>;
    andWhereLike(columnName: string): OeremQuery<T>;
    orWhereLike(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orWhereLike(callback: QueryCallback): OeremQuery<T>;
    orWhereLike(object: any): OeremQuery<T>;
    orWhereLike(columnName: keyof T, value: any): OeremQuery<T>;
    orWhereLike(columnName: string, value: any): OeremQuery<T>;
    orWhereLike(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    orWhereLike(columnName: string, operator: string, value: any): OeremQuery<T>;
    orWhereLike(left: any, operator: string, right: any): OeremQuery<T>;
    orWhereLike(condition: boolean): OeremQuery<T>;
    orWhereLike(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orWhereLike(columnName: keyof T): OeremQuery<T>;
    orWhereLike(columnName: string): OeremQuery<T>;
    whereILike(raw: string | Knex.Raw<any>): OeremQuery<T>;
    whereILike(callback: QueryCallback): OeremQuery<T>;
    whereILike(object: any): OeremQuery<T>;
    whereILike(columnName: keyof T, value: any): OeremQuery<T>;
    whereILike(columnName: string, value: any): OeremQuery<T>;
    whereILike(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    whereILike(columnName: string, operator: string, value: any): OeremQuery<T>;
    whereILike(left: any, operator: string, right: any): OeremQuery<T>;
    whereILike(condition: boolean): OeremQuery<T>;
    whereILike(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    whereILike(columnName: keyof T): OeremQuery<T>;
    whereILike(columnName: string): OeremQuery<T>;
    andWhereILike(raw: string | Knex.Raw<any>): OeremQuery<T>;
    andWhereILike(callback: QueryCallback): OeremQuery<T>;
    andWhereILike(object: any): OeremQuery<T>;
    andWhereILike(columnName: keyof T, value: any): OeremQuery<T>;
    andWhereILike(columnName: string, value: any): OeremQuery<T>;
    andWhereILike(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    andWhereILike(columnName: string, operator: string, value: any): OeremQuery<T>;
    andWhereILike(left: any, operator: string, right: any): OeremQuery<T>;
    andWhereILike(condition: boolean): OeremQuery<T>;
    andWhereILike(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    andWhereILike(columnName: keyof T): OeremQuery<T>;
    andWhereILike(columnName: string): OeremQuery<T>;
    orWhereILike(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orWhereILike(callback: QueryCallback): OeremQuery<T>;
    orWhereILike(object: any): OeremQuery<T>;
    orWhereILike(columnName: keyof T, value: any): OeremQuery<T>;
    orWhereILike(columnName: string, value: any): OeremQuery<T>;
    orWhereILike(columnName: keyof T, operator: ComparisonOperator, value: any): OeremQuery<T>;
    orWhereILike(columnName: string, operator: string, value: any): OeremQuery<T>;
    orWhereILike(left: any, operator: string, right: any): OeremQuery<T>;
    orWhereILike(condition: boolean): OeremQuery<T>;
    orWhereILike(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orWhereILike(columnName: keyof T): OeremQuery<T>;
    orWhereILike(columnName: string): OeremQuery<T>;
    whereNull(columnName: keyof T): OeremQuery<T>;
    whereNull(columnName: string): OeremQuery<T>;
    orWhereNull(columnName: keyof T): OeremQuery<T>;
    orWhereNull(columnName: string): OeremQuery<T>;
    whereNotNull(columnName: keyof T): OeremQuery<T>;
    whereNotNull(columnName: string): OeremQuery<T>;
    orWhereNotNull(columnName: keyof T): OeremQuery<T>;
    orWhereNotNull(columnName: string): OeremQuery<T>;
    whereBetween(columnName: keyof T, range: keyof T): OeremQuery<T>;
    whereBetween(columnName: string, range: any): OeremQuery<T>;
    orWhereBetween(columnName: keyof T, range: keyof T): OeremQuery<T>;
    orWhereBetween(columnName: string, range: any): OeremQuery<T>;
    andWhereBetween(columnName: keyof T, range: keyof T): OeremQuery<T>;
    andWhereBetween(columnName: string, range: any): OeremQuery<T>;
    whereNotBetween(columnName: keyof T, range: keyof T): OeremQuery<T>;
    whereNotBetween(columnName: string, range: any): OeremQuery<T>;
    orWhereNotBetween(columnName: keyof T, range: keyof T): OeremQuery<T>;
    orWhereNotBetween(columnName: string, range: any): OeremQuery<T>;
    andWhereNotBetween(columnName: keyof T, range: keyof T): OeremQuery<T>;
    andWhereNotBetween(columnName: string, range: any): OeremQuery<T>;
    whereJsonObject(columnName: any, value: any): OeremQuery<T>;
    orWhereJsonObject(columnName: any, value: any): OeremQuery<T>;
    andWhereJsonObject(columnName: any, value: any): OeremQuery<T>;
    whereNotJsonObject(columnName: any, value: any): OeremQuery<T>;
    orWhereNotJsonObject(columnName: any, value: any): OeremQuery<T>;
    andWhereNotJsonObject(columnName: any, value: any): OeremQuery<T>;
    whereJsonPath(columnName: any, jsonPath: string, operator: string, value: any): OeremQuery<T>;
    orWhereJsonPath(columnName: any, jsonPath: string, operator: string, value: any): OeremQuery<T>;
    andWhereJsonPath(columnName: any, jsonPath: string, operator: string, value: any): OeremQuery<T>;
    whereJsonSupersetOf(columnName: any, value: any): OeremQuery<T>;
    orWhereJsonSupersetOf(columnName: any, value: any): OeremQuery<T>;
    andWhereJsonSupersetOf(columnName: any, value: any): OeremQuery<T>;
    whereJsonNotSupersetOf(columnName: any, value: any): OeremQuery<T>;
    orWhereJsonNotSupersetOf(columnName: any, value: any): OeremQuery<T>;
    andWhereJsonNotSupersetOf(columnName: any, value: any): OeremQuery<T>;
    whereJsonSubsetOf(columnName: any, value: any): OeremQuery<T>;
    orWhereJsonSubsetOf(columnName: any, value: any): OeremQuery<T>;
    andWhereJsonSubsetOf(columnName: any, value: any): OeremQuery<T>;
    whereJsonNotSubsetOf(columnName: any, value: any): OeremQuery<T>;
    orWhereJsonNotSubsetOf(columnName: any, value: any): OeremQuery<T>;
    andWhereJsonNotSubsetOf(columnName: any, value: any): OeremQuery<T>;
    groupBy(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    groupBy(raw: string | Knex.Raw<any>): OeremQuery<T>;
    groupBy(columnName: "*"): OeremQuery<T>;
    // groupBy(columnNames: readonly ColNameUT[]): OeremQuery<T>;

    groupBy(columnNames: any[]): OeremQuery<T>;
    groupByRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    groupByRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orderBy(columnName: keyof T, order: "asc" | "desc", nulls: "first" | "last"): OeremQuery<T>;
    orderBy(columnName: keyof T, order: "asc" | "desc"): OeremQuery<T>;
    orderBy(columnDefs: keyof T): OeremQuery<T>;
    orderBy(columnDefs: any[]): OeremQuery<T>;
    orderByRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orderByRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    partitionBy(columnName: keyof T, order: "asc" | "desc", nulls: "first" | "last"): OeremQuery<T>;
    partitionBy(columnName: any, order: string, nulls: string): OeremQuery<T>;
    partitionBy(columnDefs: keyof T): OeremQuery<T>;
    partitionBy(columnDefs: any[]): OeremQuery<T>;
    union(callback: QueryCallback, wrap: boolean): OeremQuery<T>;
    union(callbacks: QueryCallback): OeremQuery<T>;
    unionAll(callback: QueryCallback, wrap: boolean): OeremQuery<T>;
    unionAll(callbacks: QueryCallback): OeremQuery<T>;
    intersect(callback: QueryCallback, wrap: boolean): OeremQuery<T>;
    intersect(callbacks: QueryCallback): OeremQuery<T>;
    except(callback: QueryCallback, wrap: boolean): OeremQuery<T>;
    except(callbacks: QueryCallback): OeremQuery<T>;
    having(column: keyof T, operator: ComparisonOperator, value: keyof T): OeremQuery<T>;
    having(column: any, operator: string, value: any): OeremQuery<T>;
    having(raw: string | Knex.Raw<any>): OeremQuery<T>;
    having(callback: QueryCallback): OeremQuery<T>;
    andHaving(column: keyof T, operator: ComparisonOperator, value: keyof T): OeremQuery<T>;
    andHaving(column: any, operator: string, value: any): OeremQuery<T>;
    andHaving(raw: string | Knex.Raw<any>): OeremQuery<T>;
    andHaving(callback: QueryCallback): OeremQuery<T>;
    havingRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    havingRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orHaving(column: keyof T, operator: ComparisonOperator, value: keyof T): OeremQuery<T>;
    orHaving(column: any, operator: string, value: any): OeremQuery<T>;
    orHaving(raw: string | Knex.Raw<any>): OeremQuery<T>;
    orHaving(callback: QueryCallback): OeremQuery<T>;
    orHavingRaw(sql: string | Knex.Raw<any>, bindings: any[]): OeremQuery<T>;
    orHavingRaw(raw: string | Knex.Raw<any>): OeremQuery<T>;
    havingIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    havingIn(columnName: string, values: any[]): OeremQuery<T>;
    orHavingNotBetween(columnName: keyof T, values: keyof T): OeremQuery<T>;
    orHavingNotBetween(columnName: string, values: any[]): OeremQuery<T>;
    havingNotBetween(columnName: keyof T, values: keyof T): OeremQuery<T>;
    havingNotBetween(columnName: string, values: any[]): OeremQuery<T>;
    orHavingBetween(columnName: keyof T, values: keyof T): OeremQuery<T>;
    orHavingBetween(columnName: string, values: any[]): OeremQuery<T>;
    havingBetween(columnName: keyof T, values: keyof T): OeremQuery<T>;
    havingBetween(columnName: string, values: any[]): OeremQuery<T>;
    havingNotIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    havingNotIn(columnName: string, values: any[]): OeremQuery<T>;
    andHavingNotIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    andHavingNotIn(columnName: string, values: any[]): OeremQuery<T>;
    orHavingNotIn(columnName: keyof T, values: keyof T): OeremQuery<T>;
    orHavingNotIn(columnName: string, values: any[]): OeremQuery<T>;
    havingNull(columnName: keyof T): OeremQuery<T>;
    havingNull(columnName: string): OeremQuery<T>;
    havingNotNull(columnName: keyof T): OeremQuery<T>;
    havingNotNull(columnName: string): OeremQuery<T>;
    orHavingNull(columnName: keyof T): OeremQuery<T>;
    orHavingNull(columnName: string): OeremQuery<T>;
    orHavingNotNull(columnName: keyof T): OeremQuery<T>;
    orHavingNotNull(columnName: string): OeremQuery<T>;
    count(columnName: any, options: any): OeremQuery<T>;
    count(columnName: any): OeremQuery<T>;
    count(columnNames: any[]): OeremQuery<T>;
    count(aliases: any): OeremQuery<T>;
    // count(aliases: TAliases): OeremQuery<T>;
    countDistinct(columnName: any, options: any): OeremQuery<T>;
    countDistinct(columnNames: any[]): OeremQuery<T>;
    // countDistinct(aliases: TAliases): OeremQuery<T>;
    min(columnName: keyof T, options: any): OeremQuery<T>;
    min(columnName: any): OeremQuery<T>;
    min(columnNames: keyof T): OeremQuery<T>;
    // min(aliases: TAliases): OeremQuery<T>;
    min(columnNames: any[]): OeremQuery<T>;
    min(aliases: any): OeremQuery<T>;
    max(columnName: keyof T, options: any): OeremQuery<T>;
    max(columnName: any): OeremQuery<T>;
    max(columnNames: keyof T): OeremQuery<T>;
    // max(aliases: TAliases): OeremQuery<T>;
    max(columnNames: any[]): OeremQuery<T>;
    max(aliases: any): OeremQuery<T>;
    sum(columnName: keyof T, options: any): OeremQuery<T>;
    sum(columnName: any): OeremQuery<T>;
    sum(columnNames: keyof T): OeremQuery<T>;
    // sum(aliases: TAliases): OeremQuery<T>;
    sum(columnNames: any[]): OeremQuery<T>;
    sum(aliases: any): OeremQuery<T>;
    sumDistinct(columnName: keyof T, options: any): OeremQuery<T>;
    sumDistinct(columnNames: keyof T): OeremQuery<T>;
    // sumDistinct(aliases: TAliases): OeremQuery<T>;
    sumDistinct(columnNames: any[]): OeremQuery<T>;
    avg(columnName: keyof T, options: any): OeremQuery<T>;
    avg(columnName: any): OeremQuery<T>;
    avg(columnNames: keyof T): OeremQuery<T>;
    // avg(aliases: TAliases): OeremQuery<T>;
    avg(columnNames: any[]): OeremQuery<T>;
    avg(aliases: any): OeremQuery<T>;
    avgDistinct(columnName: keyof T, options: any): OeremQuery<T>;
    avgDistinct(columnNames: keyof T): OeremQuery<T>;
    // avgDistinct(aliases: TAliases): OeremQuery<T>;
    avgDistinct(columnNames: any[]): OeremQuery<T>;
    // rank(alias: TAlias, raw: QueryCallback): OeremQuery<T>;
    // rank(alias: TAlias, orderBy: keyof T, partitionBy: keyof T): OeremQuery<T>;
    // denseRank(alias: TAlias, raw: QueryCallback): OeremQuery<T>;
    // denseRank(alias: TAlias, orderBy: keyof T, partitionBy: keyof T): OeremQuery<T>;
    // rowNumber(alias: TAlias, raw: QueryCallback): OeremQuery<T>;
    // rowNumber(alias: TAlias, orderBy: keyof T, partitionBy: keyof T): OeremQuery<T>;
    // first(): OeremQuery<T>;
    // first(subQueryBuilders: any[]): OeremQuery<T>;
    // first(aliases: string | Record<string, string>): OeremQuery<T>;
    // first(columnName: "*"): OeremQuery<T>;
    // first(columnNames: readonly ColNameUT[]): OeremQuery<T>;
    // first(columnNames: any[]): OeremQuery<T>;
    // updateFrom(tableName: TTable): OeremQuery<T>;
    // updateFrom(tableName: any): OeremQuery<T>;
    // updateFrom(callback: Function): OeremQuery<T>;
    // updateFrom(raw: string|Knex.Raw<any>): OeremQuery<T>;

    limit(limit: number): OeremQuery<T>;
    offset(offset: number): OeremQuery<T>;
}
